/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.indaba.lostandfound.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.ShardedModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Item service. Represents a row in the &quot;lfvo_Item&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.indaba.lostandfound.model.impl.ItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.indaba.lostandfound.model.impl.ItemImpl}.
 * </p>
 *
 * @author aritz
 * @see Item
 * @see net.indaba.lostandfound.model.impl.ItemImpl
 * @see net.indaba.lostandfound.model.impl.ItemModelImpl
 * @generated
 */
@ProviderType
public interface ItemModel extends BaseModel<Item>, ShardedModel, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item model instance should use the {@link Item} interface instead.
	 */

	/**
	 * Returns the primary key of this item.
	 *
	 * @return the primary key of this item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item.
	 *
	 * @param primaryKey the primary key of this item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this item.
	 *
	 * @return the uuid of this item
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this item.
	 *
	 * @param uuid the uuid of this item
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the item ID of this item.
	 *
	 * @return the item ID of this item
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this item.
	 *
	 * @param itemId the item ID of this item
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the group ID of this item.
	 *
	 * @return the group ID of this item
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this item.
	 *
	 * @param groupId the group ID of this item
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this item.
	 *
	 * @return the company ID of this item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this item.
	 *
	 * @param companyId the company ID of this item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this item.
	 *
	 * @return the user ID of this item
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this item.
	 *
	 * @param userId the user ID of this item
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this item.
	 *
	 * @return the user uuid of this item
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this item.
	 *
	 * @param userUuid the user uuid of this item
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this item.
	 *
	 * @return the create date of this item
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this item.
	 *
	 * @param createDate the create date of this item
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this item.
	 *
	 * @return the modified date of this item
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this item.
	 *
	 * @param modifiedDate the modified date of this item
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the object ID of this item.
	 *
	 * @return the object ID of this item
	 */
	@AutoEscape
	public String getObjectId();

	/**
	 * Sets the object ID of this item.
	 *
	 * @param objectId the object ID of this item
	 */
	public void setObjectId(String objectId);

	/**
	 * Returns the name of this item.
	 *
	 * @return the name of this item
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this item.
	 *
	 * @param name the name of this item
	 */
	public void setName(String name);

	/**
	 * Returns the type of this item.
	 *
	 * @return the type of this item
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this item.
	 *
	 * @param type the type of this item
	 */
	public void setType(String type);

	/**
	 * Returns the description of this item.
	 *
	 * @return the description of this item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this item.
	 *
	 * @param description the description of this item
	 */
	public void setDescription(String description);

	/**
	 * Returns the lat of this item.
	 *
	 * @return the lat of this item
	 */
	public long getLat();

	/**
	 * Sets the lat of this item.
	 *
	 * @param lat the lat of this item
	 */
	public void setLat(long lat);

	/**
	 * Returns the lng of this item.
	 *
	 * @return the lng of this item
	 */
	public long getLng();

	/**
	 * Sets the lng of this item.
	 *
	 * @param lng the lng of this item
	 */
	public void setLng(long lng);

	/**
	 * Returns the field2 of this item.
	 *
	 * @return the field2 of this item
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this item is field2.
	 *
	 * @return <code>true</code> if this item is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this item is field2.
	 *
	 * @param field2 the field2 of this item
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this item.
	 *
	 * @return the field3 of this item
	 */
	public int getField3();

	/**
	 * Sets the field3 of this item.
	 *
	 * @param field3 the field3 of this item
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this item.
	 *
	 * @return the field4 of this item
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this item.
	 *
	 * @param field4 the field4 of this item
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this item.
	 *
	 * @return the field5 of this item
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this item.
	 *
	 * @param field5 the field5 of this item
	 */
	public void setField5(String field5);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(net.indaba.lostandfound.model.Item item);

	@Override
	public int hashCode();

	@Override
	public CacheModel<net.indaba.lostandfound.model.Item> toCacheModel();

	@Override
	public net.indaba.lostandfound.model.Item toEscapedModel();

	@Override
	public net.indaba.lostandfound.model.Item toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}