package net.indaba.lostandfound.firebase;

import java.io.UnsupportedEncodingException;
import java.util.HashMap;
import java.util.Map;

import com.liferay.message.boards.kernel.model.MBMessage;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.util.portlet.PortletProps;

import net.indaba.lostandfound.model.Item;
import net.indaba.lostandfound.service.ItemLocalServiceUtil;
import net.thegreshams.firebase4j.error.FirebaseException;
import net.thegreshams.firebase4j.error.JacksonUtilityException;
import net.thegreshams.firebase4j.model.FirebaseResponse;
import net.thegreshams.firebase4j.service.Firebase;

/**
 * Firebase sync utility class. Considers objects as shared; uses the
 * autogenerated Firebase key
 * 
 * @author yzhan
 *
 */
public class FirebaseMBMessageSyncUtil {

	private static FirebaseMBMessageSyncUtil instance;
	
	FirebaseItemSyncUtil itemUtil = FirebaseItemSyncUtil.getInstance();

	private String FB_URI = PortletProps.get("firebase.url") + "/messages";
	private String FB_Item_URI = PortletProps.get("firebase.url") + "/items";

	private FirebaseMBMessageSyncUtil() {
		super();
	}

	public static FirebaseMBMessageSyncUtil getInstance() {
		if (instance == null) {
			instance = new FirebaseMBMessageSyncUtil();
		}
		return instance;
	}

	public boolean isSyncEnabled() {
		String firebaseSyncEnabled = PortletProps.get("firebase.sync.enabled");
		return Boolean.parseBoolean(firebaseSyncEnabled);
	}

	public void add(MBMessage message)
			throws FirebaseException, UnsupportedEncodingException, JacksonUtilityException, PortalException {
		Firebase firebase = new Firebase(FB_URI);
		Map<String, Object> objectMap = toMap(message);
		FirebaseResponse response = firebase.post(objectMap);
		if (response.getCode() == 200) {
			_log.debug("Firebase create sucessful");
			String fbMessageKey = (String) response.getBody().get("name");
			setRelation(message.getClassPK(), fbMessageKey, true);
		} else {
			_log.debug("Firebase create unsuccessful. Response code: " + response.getCode());
		}
	}

	private void setRelation(long itemId, String fbMessageKey, boolean add)
			throws FirebaseException, UnsupportedEncodingException, JacksonUtilityException, PortalException {
		Firebase firebase = new Firebase(FB_Item_URI);
		Item item = ItemLocalServiceUtil.getItem(itemId);
		String fbItemKey = itemUtil.getFirebaseKey(item);

		FirebaseResponse response;
		if (add) {
			Map<String, Object> messagesMap = new HashMap<String, Object>();
			messagesMap.put(fbMessageKey, true);
			response = firebase.patch("/" + itemUtil.getItemPath(item) + "/" + fbItemKey + "/messages", messagesMap);
		} else {
			response = firebase.delete("/" + itemUtil.getItemPath(item) + "/" + fbItemKey + "/messages/" + fbMessageKey);
		}
		if (response.getCode() == 200) {
			_log.debug("Firebase relation modified");
		} else {
			_log.debug("Firebase relation not modified");
		}
	}

	public void update(MBMessage message) throws FirebaseException, UnsupportedEncodingException, JacksonUtilityException {
		update(message, getFirebaseKey(message));
	}

	public void update(MBMessage message, String key)
			throws FirebaseException, UnsupportedEncodingException, JacksonUtilityException {
		Firebase firebase = new Firebase(FB_URI);
		Map<String, Object> map = toMap(message);
		FirebaseResponse response = firebase.patch("/" + key, map);
		if (response.getCode() == 200) {
			_log.debug("Firebase update sucessful");
		} else {
			_log.debug("Firebase update unsuccessful. Response code: " + response.getCode());
		}
	}

	public void addOrUpdate(MBMessage message)
			throws FirebaseException, JacksonUtilityException, UnsupportedEncodingException, PortalException {
		String key = getFirebaseKey(message);
		if (key != null) { /* Message exists already in Firebase: update */
			update(message, key);
		} else { /* Message does not exist in Firebase: create */
			add(message);
		}
	}

	public void delete(MBMessage message)
			throws FirebaseException, UnsupportedEncodingException, JacksonUtilityException, PortalException {
		Firebase firebase = new Firebase(FB_URI);

		String key = getFirebaseKey(message);
		FirebaseResponse response;
		if (key != null) {
			response = firebase.delete("/" + key);
			if (response.getCode() == 200) {
				_log.debug("Firebase delete sucessful");
				setRelation(message.getClassPK(), key, false);
			} else {
				_log.debug("Firebase delete unsuccessful. Response code: " + response.getCode());
			}
		} else {
			_log.debug("Could not find message with id " + message.getPrimaryKeyObj());
		}
	}

	private String getFirebaseKey(MBMessage message) throws FirebaseException, UnsupportedEncodingException {
		Firebase firebase = new Firebase(FB_URI);
		firebase.addQuery("orderBy", "\"id\"");
		firebase.addQuery("equalTo", String.valueOf(message.getPrimaryKey()));
		FirebaseResponse response = firebase.get();
		if (response.getCode() == 200) {
			Map<String, Object> responseMap = response.getBody();
			Object[] keys = responseMap.keySet().toArray();
			if (keys.length > 0) {
				return (String) keys[0];
			} else {
				return null;
			}
		} else {
			_log.debug("Firebase get key unsuccessfull. Response code: " + response.getCode());
		}
		return null;
	}

	private Map<String, Object> toMap(MBMessage message) {
		// TODO parse description and title maps
		Map<String, Object> messageMap = message.getModelAttributes();
		messageMap.remove("messageId");
		messageMap.put("id", message.getMessageId());
		return messageMap;
	};

	private MBMessage parseMap(Map<String, Object> map) {
		// TODO implement method body
		return null;
	};

	private final Log _log = LogFactoryUtil.getLog(FirebaseMBMessageSyncUtil.class);

}
